/* Verilog module instantiation template generated by SCUBA Diamond Version 3.4.0.80 */
/* Module Version: 5.7 */
/* Thu Mar 09 12:55:36 2017 */

/* parameterized module instance */
fifo_submean __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), .AlmostEmpty( ), 
    .AlmostFull( ));
