/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.9_x64\ispfpga\bin\nt64\scuba.exe -w -n fifo_horizontal -lang verilog -synth lse -bus_exp 7 -bb -arch xo3c00a -type ebfifo -depth 16 -width 16 -rwidth 16 -no_enable -pe 4 -pf 15  */
/* Mon Apr 10 02:50:38 2017 */


`timescale 1 ns / 1 ps
module fifo_horizontal (Data, WrClock, RdClock, WrEn, RdEn, Reset, 
    RPReset, Q, Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [15:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [15:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire scuba_vhi;
    wire Empty_int;
    wire Full_int;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam fifo_horizontal_0_0.FULLPOINTER1 = "0b00000011110000" ;
    defparam fifo_horizontal_0_0.FULLPOINTER = "0b00000100000000" ;
    defparam fifo_horizontal_0_0.AFPOINTER1 = "0b00000011100000" ;
    defparam fifo_horizontal_0_0.AFPOINTER = "0b00000011110000" ;
    defparam fifo_horizontal_0_0.AEPOINTER1 = "0b00000001010000" ;
    defparam fifo_horizontal_0_0.AEPOINTER = "0b00000001000000" ;
    defparam fifo_horizontal_0_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_horizontal_0_0.GSR = "DISABLED" ;
    defparam fifo_horizontal_0_0.RESETMODE = "ASYNC" ;
    defparam fifo_horizontal_0_0.REGMODE = "NOREG" ;
    defparam fifo_horizontal_0_0.CSDECODE_R = "0b11" ;
    defparam fifo_horizontal_0_0.CSDECODE_W = "0b11" ;
    defparam fifo_horizontal_0_0.DATA_WIDTH_R = 18 ;
    defparam fifo_horizontal_0_0.DATA_WIDTH_W = 18 ;
    FIFO8KB fifo_horizontal_0_0 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .DI4(Data[4]), .DI5(Data[5]), .DI6(Data[6]), .DI7(Data[7]), 
        .DI8(Data[8]), .DI9(Data[9]), .DI10(Data[10]), .DI11(Data[11]), 
        .DI12(Data[12]), .DI13(Data[13]), .DI14(Data[14]), .DI15(Data[15]), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(scuba_vhi), 
        .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q[9]), .DO1(Q[10]), .DO2(Q[11]), 
        .DO3(Q[12]), .DO4(Q[13]), .DO5(Q[14]), .DO6(Q[15]), .DO7(), .DO8(), 
        .DO9(Q[0]), .DO10(Q[1]), .DO11(Q[2]), .DO12(Q[3]), .DO13(Q[4]), 
        .DO14(Q[5]), .DO15(Q[6]), .DO16(Q[7]), .DO17(Q[8]), .EF(Empty_int), 
        .AEF(AlmostEmpty), .AFF(AlmostFull), .FF(Full_int));

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar end

endmodule
