/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.8 */
/* Mon Apr 10 02:50:38 2017 */

/* parameterized module instance */
fifo_horizontal __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), 
    .RdEn( ), .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), 
    .AlmostEmpty( ), .AlmostFull( ));
