/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.7 */
/* Sun Apr 09 21:04:41 2017 */

/* parameterized module instance */
pll2 __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
