/* Verilog module instantiation template generated by SCUBA Diamond Version 3.4.0.80 */
/* Module Version: 5.7 */
/* Wed Mar 01 14:38:42 2017 */

/* parameterized module instance */
pll1 __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), .LOCK( ));
