/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 5.8 */
/* Sat Mar 11 17:25:31 2017 */

/* parameterized module instance */
fifo_beam_forming __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), 
    .RdEn( ), .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), 
    .AlmostEmpty( ), .AlmostFull( ));
