/* Verilog module instantiation template generated by SCUBA Diamond Version 3.4.0.80 */
/* Module Version: 5.7 */
/* Tue Mar 07 17:27:20 2017 */

/* parameterized module instance */
pll1 __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
