/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 2.8 */
/* C:\lscc\diamond\3.8_x64\ispfpga\bin\nt64\scuba.exe -w -n roughness_signals -lang verilog -synth synplify -bus_exp 7 -bb -arch xo3c00a -type rom -addr_width 10 -num_rows 1024 -data_width 16 -outdata REGISTERED -memfile d:/uiuc/2017_spring/ece_396/i2s_fifo_zcr_ste_submean_bform_r/roughness_signals.mem -memformat hex  */
/* Tue Apr 11 17:32:15 2017 */


`timescale 1 ns / 1 ps
module roughness_signals (Address, OutClock, OutClockEn, Reset, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [9:0] Address;
    input wire OutClock;
    input wire OutClockEn;
    input wire Reset;
    output wire [15:0] Q;

    wire qdataout15_ffin;
    wire mdL0_0_3;
    wire mdL0_0_2;
    wire mdL0_0_1;
    wire mdL0_0_0;
    wire qdataout14_ffin;
    wire mdL0_1_3;
    wire mdL0_1_2;
    wire mdL0_1_1;
    wire mdL0_1_0;
    wire qdataout13_ffin;
    wire mdL0_2_3;
    wire mdL0_2_2;
    wire mdL0_2_1;
    wire mdL0_2_0;
    wire qdataout12_ffin;
    wire mdL0_3_3;
    wire mdL0_3_2;
    wire mdL0_3_1;
    wire mdL0_3_0;
    wire qdataout11_ffin;
    wire mdL0_4_3;
    wire mdL0_4_2;
    wire mdL0_4_1;
    wire mdL0_4_0;
    wire qdataout10_ffin;
    wire mdL0_5_3;
    wire mdL0_5_2;
    wire mdL0_5_1;
    wire mdL0_5_0;
    wire qdataout9_ffin;
    wire mdL0_6_3;
    wire mdL0_6_2;
    wire mdL0_6_1;
    wire mdL0_6_0;
    wire qdataout8_ffin;
    wire mdL0_7_3;
    wire mdL0_7_2;
    wire mdL0_7_1;
    wire mdL0_7_0;
    wire qdataout7_ffin;
    wire mdL0_8_3;
    wire mdL0_8_2;
    wire mdL0_8_1;
    wire mdL0_8_0;
    wire qdataout6_ffin;
    wire mdL0_9_3;
    wire mdL0_9_2;
    wire mdL0_9_1;
    wire mdL0_9_0;
    wire qdataout5_ffin;
    wire mdL0_10_3;
    wire mdL0_10_2;
    wire mdL0_10_1;
    wire mdL0_10_0;
    wire qdataout4_ffin;
    wire mdL0_11_3;
    wire mdL0_11_2;
    wire mdL0_11_1;
    wire mdL0_11_0;
    wire qdataout3_ffin;
    wire mdL0_12_3;
    wire mdL0_12_2;
    wire mdL0_12_1;
    wire mdL0_12_0;
    wire qdataout2_ffin;
    wire mdL0_13_3;
    wire mdL0_13_2;
    wire mdL0_13_1;
    wire mdL0_13_0;
    wire qdataout1_ffin;
    wire mdL0_14_3;
    wire mdL0_14_2;
    wire mdL0_14_1;
    wire mdL0_14_0;
    wire qdataout0_ffin;
    wire mdL0_15_3;
    wire mdL0_15_2;
    wire mdL0_15_1;
    wire mdL0_15_0;

    FD1P3DX FF_15 (.D(qdataout15_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[15]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(qdataout14_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[14]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(qdataout13_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[13]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(qdataout12_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[12]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(qdataout11_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[11]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(qdataout10_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[10]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(qdataout9_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(qdataout8_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(qdataout7_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(qdataout6_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(qdataout5_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(qdataout4_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(qdataout3_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(qdataout2_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(qdataout1_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(qdataout0_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    defparam mem_0_15.initval = 256'h00FFFFC00007F801FFFF80000FFFFC0000FFFFE7FFF80001FFFFC00FF00003FF ;
    ROM256X1A mem_0_15 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_0));

    defparam mem_0_14.initval = 256'h00E001C3FE07F801FFFF80000FFFFC0000FFFFE7FFF87FF1E007C00FF00003FF ;
    ROM256X1A mem_0_14 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_0));

    defparam mem_0_13.initval = 256'hFCD8064C0187F801E00387FE0F803C3FF8F00FE7E0399FCD9839C00FF0FFE380 ;
    ROM256X1A mem_0_13 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_0));

    defparam mem_0_12.initval = 256'hF2B60A95F967F8F1980C99F1CC7FCCCFE6CEF1E71CCAAFAB57DACF8FF33F9B70 ;
    ROM256X1A mem_0_12 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_0));

    defparam mem_0_11.initval = 256'hE91D10DEF4D41B0D54152A0D2A60D557D5A912E6931BE37904CE506C354F56CD ;
    ROM256X1A mem_0_11 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_4_0));

    defparam mem_0_10.initval = 256'hFEDC29406D622D090221BE6B811F63FBBC852665CB4414358F697F5BD010F26A ;
    ROM256X1A mem_0_10 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_5_0));

    defparam mem_0_9.initval = 256'h5ABE926DF3C5F86AC7529C9D8641DCF05AC9552043D4D4DEC365F7CE0D866B62 ;
    ROM256X1A mem_0_9 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_6_0));

    defparam mem_0_8.initval = 256'h9E17C5A79FDA4B36BCA0C1CA9B535D7DBE732766D05562ACFA1CB2AB5A5E1DF6 ;
    ROM256X1A mem_0_8 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_7_0));

    defparam mem_0_7.initval = 256'hFADDC46979D341DEE9CD4ABDAF50B7E727653BB6934DB7E81FAA2464E251F862 ;
    ROM256X1A mem_0_7 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_8_0));

    defparam mem_0_6.initval = 256'h8890DEAF3F15B484712E6CB7E3F828BF453E38808D762E2516536652426D39FA ;
    ROM256X1A mem_0_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_9_0));

    defparam mem_0_5.initval = 256'h13C8408D64F93A5081B4C4C5DAED45E781F177B1B50EAD2C248B0E3DBFBBF36C ;
    ROM256X1A mem_0_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_10_0));

    defparam mem_0_4.initval = 256'h078D2DD4DCA65E783E1E199779D1B36D3A2545F11D10941C4AA4D32C7290A475 ;
    ROM256X1A mem_0_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_11_0));

    defparam mem_0_3.initval = 256'h2A7992500C19AACF689CAC42E4FA3D4D576788B65309681F9ABF000D0419CF50 ;
    ROM256X1A mem_0_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_12_0));

    defparam mem_0_2.initval = 256'h50DC6FFC7D0C8BB4B7B722720C1FF5E36F5ABB05A859483BD1A982AEB2ED0B48 ;
    ROM256X1A mem_0_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_13_0));

    defparam mem_0_1.initval = 256'h32BED47E4C6CC5548A4CEA85DC12723A52FEB45656217099C69556E37624A1F8 ;
    ROM256X1A mem_0_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_14_0));

    defparam mem_0_0.initval = 256'h2A5E4F4F2B3DF1CC2F3A409EC6E853D627C22B37F58A176A0C871C81F2014F18 ;
    ROM256X1A mem_0_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_15_0));

    defparam mem_1_15.initval = 256'hFE00003FFFF00003FFF87FFFE00007FFFF07FFC0000FFFFE00007FFFE0000400 ;
    ROM256X1A mem_1_15 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_1));

    defparam mem_1_14.initval = 256'hFE00003FFFF00003FFF87F81E3FFC7807F07FFC0000FFFFE00007FFFE0000400 ;
    ROM256X1A mem_1_14 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_1));

    defparam mem_1_13.initval = 256'h0E1FF83C00F1FFE3E3F8787E64FF367F8F07FFC7FF8F003E0FF87000E1FC040F ;
    ROM256X1A mem_1_13 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_1));

    defparam mem_1_12.initval = 256'h32600633EF327F9B1C38667EAD7EAD63B70700C9FE6CE3CE70066C0326038433 ;
    ROM256X1A mem_1_12 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_1));

    defparam mem_1_11.initval = 256'h56A7E5AB1156BF529CD85547183DE6DCDB06C3527D5A9C52B7E54B054A6244D5 ;
    ROM256X1A mem_1_11 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_4_1));

    defparam mem_1_10.initval = 256'h8C4BD706920C1EE7DD687E3AEB9E957D9174BDB8FBCC5CC7D9D79E086699257E ;
    ROM256X1A mem_1_10 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_5_1));

    defparam mem_1_9.initval = 256'h74BFB31A5715CF167CC339E2B0394111B1A1E058BDAB95A732385A84A992547D ;
    ROM256X1A mem_1_9 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_6_1));

    defparam mem_1_8.initval = 256'hC1AD496F91FFFC7DD75C1D6B6DCA43C7E7CD054FB200F994939374DB783326C2 ;
    ROM256X1A mem_1_8 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_7_1));

    defparam mem_1_7.initval = 256'hB12CB829D4A08CDCBF3A74D64D1FF11080DFB76B9763E8661CEE9690BC5F647D ;
    ROM256X1A mem_1_7 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_8_1));

    defparam mem_1_6.initval = 256'hD1B9CD91383E159D1A49A6D58B58390D254A7E42DCF24C82B2712DB1909D3FBA ;
    ROM256X1A mem_1_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_9_1));

    defparam mem_1_5.initval = 256'hD916D833AB66CF6242F98D69631D6F386235B9EEE550299B1BFD1DE51BF9350C ;
    ROM256X1A mem_1_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_10_1));

    defparam mem_1_4.initval = 256'h78F6BF3DADD6378C603BB2C9121457E72812EB194AFF4269C7DC3C668C6AC13A ;
    ROM256X1A mem_1_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_11_1));

    defparam mem_1_3.initval = 256'h61E0B793B2CEB8E3E582524E0EB0348BAC45023F5F2607DB28C37DEB81486EF3 ;
    ROM256X1A mem_1_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_12_1));

    defparam mem_1_2.initval = 256'hC299D1116F9BFC2FF8B5238E5B1FD773AD911878AE0DED35A83A7E0442627921 ;
    ROM256X1A mem_1_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_13_1));

    defparam mem_1_1.initval = 256'hF3B73B71A77E269A591E21104B7B01B4D868122932BAEB10C7C5483DE2828BEF ;
    ROM256X1A mem_1_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_14_1));

    defparam mem_1_0.initval = 256'h8D2976DCEB0AE95E80EB2F7EB59855DEE40E956B4FB77976CB97EB3DCCD1EA67 ;
    ROM256X1A mem_1_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_15_1));

    defparam mem_2_15.initval = 256'h01FFFF80001FFFFFFFFF00003FFFF80001FFFF8007F00003FFFF0000180007FF ;
    ROM256X1A mem_2_15 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_2));

    defparam mem_2_14.initval = 256'h01F0038FFF1FFFFFFFFF00003FFFF80001FFFF8007F03FC3800707C0180007FF ;
    ROM256X1A mem_2_14 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_2));

    defparam mem_2_13.initval = 256'h01CF3DB3FC9801FFF80F1FFE3C00F87FF1C0038007F1C0336019383C180F8700 ;
    ROM256X1A mem_2_13 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_2));

    defparam mem_2_12.initval = 256'h312CCC95F2D6067FC7F367F9B3FF398F89300C8FC7F24FAA502B5833187066C0 ;
    ROM256X1A mem_2_12 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_2));

    defparam mem_2_11.initval = 256'hCC9AC64EE87D9A9FB6152BF52B034A9045A815B33774D07CD866082A99B054A0 ;
    ROM256X1A mem_2_11 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_4_2));

    defparam mem_2_10.initval = 256'hC9A0D690587F6C3F65E09DE07ECD9FB06EC43F1CAC9E873A2CDA6380189039F0 ;
    ROM256X1A mem_2_10 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_5_2));

    defparam mem_2_9.initval = 256'h410817C53F442BAE283120CF63B75C672DBE6314E6B33600A01C8F305A474519 ;
    ROM256X1A mem_2_9 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_6_2));

    defparam mem_2_8.initval = 256'h4BCDDA78A3EF536685138386D6301B2208F875F4169E9B16A0CAD988C2877000 ;
    ROM256X1A mem_2_8 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_7_2));

    defparam mem_2_7.initval = 256'hE129A451F2B442ED3B6CAA4C0C8D36302EE9895257AE0B90CF3B805C5E5A4EB0 ;
    ROM256X1A mem_2_7 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_8_2));

    defparam mem_2_6.initval = 256'h8148DE91C34465CF07AB59334B0702656FBEBB2C691C292D9F193E6C63D2318C ;
    ROM256X1A mem_2_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_9_2));

    defparam mem_2_5.initval = 256'h2DAC4C4334CF502DCA6AAA695FD7F323A82BF65FAE65C6D82115A0A8D8FE950A ;
    ROM256X1A mem_2_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_10_2));

    defparam mem_2_4.initval = 256'h60BA8E80FD41B695418894527F66B07D598A6527E1A78DAC90140D36AE3AD719 ;
    ROM256X1A mem_2_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_11_2));

    defparam mem_2_3.initval = 256'hA96A68A3B41EA31E74F86D372AD37BC0A34F84D90BC6B93656DD1DD5CAFFD4C6 ;
    ROM256X1A mem_2_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_12_2));

    defparam mem_2_2.initval = 256'h2DCBE4F4EE78C0CCAA46472E48947BCA8136CEE72500D86DA773FDDF298A25B8 ;
    ROM256X1A mem_2_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_13_2));

    defparam mem_2_1.initval = 256'h76F84F3E9DBFBCA6F718D937458513C50261504A1CE79C6210A281DF2AB08A77 ;
    ROM256X1A mem_2_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_14_2));

    defparam mem_2_0.initval = 256'h3490D4D837936E1BD0C44D42BAD1FA59E48542C96EB327E863AEA6A5ADA436A0 ;
    ROM256X1A mem_2_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_15_2));

    defparam mem_3_15.initval = 256'hFC0000FFFFE00007FFFE03FFC0000FFFFC000380001FFFF80000FFFFC0000FFC ;
    ROM256X1A mem_3_15 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_0_3));

    defparam mem_3_14.initval = 256'hFC0000FFFFE00007FFFE03FFC3FF8E003C000380001FFFF80000FFFFC0000FFC ;
    ROM256X1A mem_3_14 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_1_3));

    defparam mem_3_13.initval = 256'h1C7FF0F803E1FFC7001E03FFCC7C4980CC7F0383FF1C00383FE0F001C7FF0FFC ;
    ROM256X1A mem_3_13 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_2_3));

    defparam mem_3_12.initval = 256'h6D9FCCC7FCE67F24C0660380D4836D415580C38C389300D9C018CE0ED9FCCF7C ;
    ROM256X1A mem_3_12 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_3_3));

    defparam mem_3_11.initval = 256'hA4A72AB60D2A9CB6B1AA736361BA367F00BCB394C6DA834ACF96A9F24AFAAC8D ;
    ROM256X1A mem_3_11 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_4_3));

    defparam mem_3_10.initval = 256'hF268BFE5F47FA21B2EFC8A5DD916A5A28C1AEBB1446CE5E0504C05172677F894 ;
    ROM256X1A mem_3_10 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_5_3));

    defparam mem_3_9.initval = 256'h969ADFE91E7F60D2CBC20C9075CF6DA672C763E9D05B5BE3771418A74903EAA6 ;
    ROM256X1A mem_3_9 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_6_3));

    defparam mem_3_8.initval = 256'hE48DEC07F37E0A36E6BBA2659E6F1A7252EE34A4ED4B4D2C3E5CEC5D6BAD929A ;
    ROM256X1A mem_3_8 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_7_3));

    defparam mem_3_7.initval = 256'h01073226BE0591FDD58402C947287BB3A057BADCE4A415C4E8392FE0B53B5B8F ;
    ROM256X1A mem_3_7 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_8_3));

    defparam mem_3_6.initval = 256'h59179F2A715A8F0D3FA295FE7FD5AD73B123830933E68C06DB3F510A214A971F ;
    ROM256X1A mem_3_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_9_3));

    defparam mem_3_5.initval = 256'h0F515BDFAD2FE265C67787AC3919FBD196FA7BCA378E5D84BEAFFF42F1164412 ;
    ROM256X1A mem_3_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_10_3));

    defparam mem_3_4.initval = 256'hA0643F792B48DB4A789A72069E0A52070CEF19979FA95320659C23C784CA11FE ;
    ROM256X1A mem_3_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_11_3));

    defparam mem_3_3.initval = 256'hCC18BC7F968AE7DA3B3EDF954A5EE55E6DA960E14061D1F80DC9BC74BDB79EB0 ;
    ROM256X1A mem_3_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_12_3));

    defparam mem_3_2.initval = 256'hA78727B4A8CA5C941F49F88237429A78703860C3B4C89148DC04C650D145C708 ;
    ROM256X1A mem_3_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_13_3));

    defparam mem_3_1.initval = 256'h2086C5813ECEB543212D8BF4DB7F71D86EAA59A6E31BE83AF51EA5BDBC5BA60F ;
    ROM256X1A mem_3_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_14_3));

    defparam mem_3_0.initval = 256'h2CF9853816E1AE37B085A82084DE65FC52AA552EACFA21A6975A3228E38C692B ;
    ROM256X1A mem_3_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(mdL0_15_3));

    MUX41 mux_15 (.D0(mdL0_0_0), .D1(mdL0_0_1), .D2(mdL0_0_2), .D3(mdL0_0_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout15_ffin));

    MUX41 mux_14 (.D0(mdL0_1_0), .D1(mdL0_1_1), .D2(mdL0_1_2), .D3(mdL0_1_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout14_ffin));

    MUX41 mux_13 (.D0(mdL0_2_0), .D1(mdL0_2_1), .D2(mdL0_2_2), .D3(mdL0_2_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout13_ffin));

    MUX41 mux_12 (.D0(mdL0_3_0), .D1(mdL0_3_1), .D2(mdL0_3_2), .D3(mdL0_3_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout12_ffin));

    MUX41 mux_11 (.D0(mdL0_4_0), .D1(mdL0_4_1), .D2(mdL0_4_2), .D3(mdL0_4_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout11_ffin));

    MUX41 mux_10 (.D0(mdL0_5_0), .D1(mdL0_5_1), .D2(mdL0_5_2), .D3(mdL0_5_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout10_ffin));

    MUX41 mux_9 (.D0(mdL0_6_0), .D1(mdL0_6_1), .D2(mdL0_6_2), .D3(mdL0_6_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout9_ffin));

    MUX41 mux_8 (.D0(mdL0_7_0), .D1(mdL0_7_1), .D2(mdL0_7_2), .D3(mdL0_7_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout8_ffin));

    MUX41 mux_7 (.D0(mdL0_8_0), .D1(mdL0_8_1), .D2(mdL0_8_2), .D3(mdL0_8_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout7_ffin));

    MUX41 mux_6 (.D0(mdL0_9_0), .D1(mdL0_9_1), .D2(mdL0_9_2), .D3(mdL0_9_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout6_ffin));

    MUX41 mux_5 (.D0(mdL0_10_0), .D1(mdL0_10_1), .D2(mdL0_10_2), .D3(mdL0_10_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout5_ffin));

    MUX41 mux_4 (.D0(mdL0_11_0), .D1(mdL0_11_1), .D2(mdL0_11_2), .D3(mdL0_11_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout4_ffin));

    MUX41 mux_3 (.D0(mdL0_12_0), .D1(mdL0_12_1), .D2(mdL0_12_2), .D3(mdL0_12_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout3_ffin));

    MUX41 mux_2 (.D0(mdL0_13_0), .D1(mdL0_13_1), .D2(mdL0_13_2), .D3(mdL0_13_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout2_ffin));

    MUX41 mux_1 (.D0(mdL0_14_0), .D1(mdL0_14_1), .D2(mdL0_14_2), .D3(mdL0_14_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout1_ffin));

    MUX41 mux_0 (.D0(mdL0_15_0), .D1(mdL0_15_1), .D2(mdL0_15_2), .D3(mdL0_15_3), 
        .SD1(Address[8]), .SD2(Address[9]), .Z(qdataout0_ffin));



    // exemplar begin
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
