/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 2.8 */
/* Tue Apr 11 17:32:15 2017 */

/* parameterized module instance */
roughness_signals __ (.Address( ), .OutClock( ), .OutClockEn( ), 
    .Reset( ), .Q( ));
