/* Verilog module instantiation template generated by SCUBA Diamond Version 3.4.0.80 */
/* Module Version: 2.7 */
/* Fri Mar 03 10:40:43 2017 */

/* parameterized module instance */
squares __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
